version: '3.9'

services:
  postgres:
    container_name: postgresql
    image: postgres:latest
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
