version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgresql_db
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres